apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cwoche-cluster
  region: us-east-1
  version: "1.27"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: python-app
        namespace: cwoche-api
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: external-dns
        namespace: default
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
        labels: { aws-usage: "cluster-ops" }
      wellKnownPolicies:
        autoScaler: true

addons:
- name: aws-ebs-csi-driver
  wellKnownPolicies: # add IAM and service account
    ebsCSIController: true


iamIdentityMappings:
  - arn: arn:aws:iam::649165755582:role/EKSUserRole
    groups:
      - system:masters
    username: cwoche-dev
    noDuplicateARNs: true # prevents shadowing of ARNs


vpc:
  id: "vpc-0909da5b1296112cd"
  cidr: "10.0.0.0/16"
  subnets:
    private:
      us-east-1a:
        id: "subnet-05101802199c8fd41"
      us-east-1b:
        id: "subnet-0f1ac25d306162b07"
  clusterEndpoints:     #api-server
    privateAccess: true
    publicAccess: true


managedNodeGroups:
  - name: cwoche-cluster-node-group-1
    instanceType: c5.xlarge
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 30
    volumeType: gp2
    ssh:
      allow: false
    privateNetworking: true
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cwoche-cluster: "owned"