apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cwoche-database
type: Opaque
data:
  postgres-password: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
  replication-password: cG9zdGdyZXM=
  ldap-password: cG9zdGdyZXM=


